---
title: "MATH567 Project Notebook"
output:
  pdf_document: default
  html_notebook: default
---


```{r}
data <- read.csv('/Users/ratna/Documents/MATH567/Project_DATA.csv', header = TRUE)

head(data)
```

```{r}
pdata <- data[2:5]
sapply(pdata, class)
interlm <- lm(BatteryLife ~ OS*Brightness*NumOfProcs, data = pdata)
replications(BatteryLife ~ OS*Brightness*NumOfProcs, data = pdata)
summary(interlm)
plot(interlm)
aob <- anova(interlm)
aob
model.tables(aov(BatteryLife ~ OS*Brightness*NumOfProcs, data = pdata) , "means")

```



```{r}
effectslm <- lm(BatteryLife ~ OS+Brightness+NumOfProcs, data = pdata)
effectsav<- anova(lm(BatteryLife ~ OS+Brightness+NumOfProcs, data = pdata))
summary(effectslm)
par(mfrow=c(2,2))

plot(effectslm)
```
```{r}
plot.design(BatteryLife ~ OS+Brightness+NumOfProcs, data = pdata, main = "Main Effects Plot")
par(3,2)
plot(BatteryLife ~ OS+Brightness+NumOfProcs, data = pdata, main = "Main Effects Plot")
```
```{r}
library("ggplot2")
se <- sd(pdata$BatteryLife)
se
ggplot(pdata, aes(x=Brightness, y=interlm$fitted.values, color=OS,group=OS)) + 
    geom_point() + 
    geom_line(size=1.2) +
    geom_ribbon(aes(ymin=interlm$fitted-se, ymax=interlm$fitted+se, fill=OS),alpha=0.3) + 
    labs(title = "Factor Interaction Brightness * OS", x= "Brightness (High, Low)", y="Battery Life", color="OS", fill="OS") + theme_classic() + theme(text=element_text(size=20))

ggplot(pdata, aes(x=Brightness, y=interlm$fitted.values, color=NumOfProcs,group=NumOfProcs)) + 
    geom_point() + 
    geom_line(size=1.2) +
    geom_ribbon(aes(ymin=interlm$fitted-se, ymax=interlm$fitted+se, fill=NumOfProcs),alpha=0.3) + 
    labs(title = "Factor Interaction Brightness * NumOfProcs", x= "Brightness (High, Low)", y="Battery Life", color="NumOfProcs", fill="NumOfProcs") + theme_classic() + theme(text=element_text(size=20))

ggplot(pdata, aes(x=OS, y=interlm$fitted.values, color=NumOfProcs,group=NumOfProcs)) + 
    geom_point() + 
    geom_line(size=1.2) +
    geom_ribbon(aes(ymin=interlm$fitted-se, ymax=interlm$fitted+se, fill=NumOfProcs),alpha=0.3) + 
    labs(title = "Factor Interaction OS * NumOfProcs", x= "OS (Win, Linux)", y="Battery Life", color="NumOfProcs", fill="NumOfProcs") + theme_classic() + theme(text=element_text(size=20))


```



```{r}
library("FrF2")
cubePlot(interlm, "OS", "NumOfProcs", "Brightness", size=0.28, abbrev=9, cex.clab	=1)
```

```{r}
library(phia)
par(mfrow=c(1,1))
IM = interactionMeans(interlm)
IM
plot(IM)

```

```{r}
library("reshape")
library(pwr)

delta <- 19; sigma <- 17 ;d <- delta/sigma
pwr.t.test(d=d, sig.level=.05, power = .90, type = 'two.sample')
 
 
ggplot(data=pdata[sample(nrow(pdata)),], aes(x=seq(1, 16, by=1), y=BatteryLife)) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=BatteryLife), vjust=1.6, color="white", size=3.5)+
  theme_minimal() + labs(x = "Results for the experiment runs")


```

```{r}
require("pid")
paretoPlot(interlm, xlab="Effect name", ylab="Magnitude of effect",
                       main="Pareto plot", legendtitle="Sign of coefficient",
                       negative=c("Negative", "grey"),
                       positive=c("Positive", "Light Blue"))
```

```{r}
a1 <- aov(BatteryLife ~ OS*Brightness*NumOfProcs, data = pdata)
plot(a1)

Tk<- TukeyHSD(x=a1,  conf.level=0.95)
plot(Tk, las=1)

```

```{r}
library(lsmeans)
interlm
leastsquare = lsmeans(interlm,
                      pairwise  ~ OS*Brightness*NumOfProcs, 
                      adjust="tukey")           ### Tukey-adjusted comparisons

leastsquare$contrasts


cld(leastsquare,
    alpha=0.05, 
    Letters=letters,      ### Use lower-case letters for .group
    adjust="tukey")

```
```{r}

library(lsmeans)

leastsquare1 <- lsmeans(interlm,
                      pairwise  ~ NumOfProcs, 
                      adjust="tukey")           ### Tukey-adjusted comparisons

leastsquar2 <- lsmeans(interlm,
                      pairwise  ~  OS, 
                      adjust="tukey")           ### Tukey-adjusted comparisons

leastsquar3 <- lsmeans(interlm,
                      pairwise  ~  Brightness, 
                      adjust="tukey")  

cld(leastsquare1,
    alpha=0.05, 
    Letters=letters,      ### Use lower-case letters for .group
    adjust="tukey")

cld(leastsquar2,
    alpha=0.05, 
    Letters=letters,      ### Use lower-case letters for .group
    adjust="tukey")

cld(leastsquar3,
    alpha=0.05, 
    Letters=letters,      ### Use lower-case letters for .group
    adjust="tukey")

```

